/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/navigation/AppSidebar.vue')['default']
    DevTweakPanel: typeof import('./src/components/dev/DevTweakPanel.vue')['default']
    HomeSection: typeof import('./src/components/home/HomeSection.vue')['default']
    NavigationItem: typeof import('./src/components/navigation/NavigationItem.vue')['default']
    PwaStatus: typeof import('./src/components/pwa/PwaStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingRow: typeof import('./src/components/settings/SettingRow.vue')['default']
    SidebarSection: typeof import('./src/components/navigation/SidebarSection.vue')['default']
    ToolHistory: typeof import('./src/components/history/ToolHistory.vue')['default']
    ToolRow: typeof import('./src/components/tools/ToolRow.vue')['default']
    ToolSearchDialog: typeof import('./src/components/search/ToolSearchDialog.vue')['default']
    ToolState: typeof import('./src/components/states/ToolState.vue')['default']
    TweakOption: typeof import('./src/components/dev/TweakOption.vue')['default']
  }
}
