/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBrandMenu: typeof import('./src/components/navigation/AppBrandMenu.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/navigation/AppSidebar.vue')['default']
    BrandMenuSummary: typeof import('./src/components/navigation/BrandMenuSummary.vue')['default']
    DevTweakPanel: typeof import('./src/components/dev/DevTweakPanel.vue')['default']
    PwaStatus: typeof import('./src/components/pwa/PwaStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSelect: typeof import('./src/components/search/SearchSelect.vue')['default']
    TagInput: typeof import('./src/components/inputs/TagInput.vue')['default']
    ToolCategorySection: typeof import('./src/components/navigation/ToolCategorySection.vue')['default']
    ToolChart: typeof import('./src/components/charts/ToolChart.vue')['default']
    ToolContentSection: typeof import('./src/components/content/ToolContentSection.vue')['default']
    ToolPageHeader: typeof import('./src/components/layout/ToolPageHeader.vue')['default']
    ToolSearchDialog: typeof import('./src/components/search/ToolSearchDialog.vue')['default']
    ToolState: typeof import('./src/components/states/ToolState.vue')['default']
    TweakOption: typeof import('./src/components/dev/TweakOption.vue')['default']
  }
}
