<template>
  <!-- The HTML is generated by the build from the Markdown in toolbox/content, and it is the same
       string the server renders for a crawler. It is the repository's own text, never a visitor's,
       which is why it can be written straight into the page. -->
  <div v-if="html" v-html="html" />
</template>

<script setup>
import { ref, watch } from 'vue'
import { useRoute } from 'vue-router'

// One lazy chunk for each tool, so a page carries its own words and nobody else's. A route with no
// content file has no entry here, and the section renders nothing.
const pages = import.meta.glob('../../../../toolbox/content/pages/*.json')

const route = useRoute()
const html = ref('')

watch(
  () => route.path,
  async (path) => {
    const load = pages[`../../../../toolbox/content/pages${path}.json`]
    if (!load) {
      html.value = ''
      return
    }

    try {
      const page = await load()
      // A slow chunk can arrive after the visitor has moved on. The page that is open wins.
      if (route.path === path) html.value = page.default.content
    } catch {
      // Content is worth reading, and worth nothing at the cost of the tool above it. An offline
      // visitor whose chunk was never cached keeps the working tool.
      html.value = ''
    }
  },
  { immediate: true },
)
</script>
