<template>
  <div class="mx-auto w-full max-w-3xl px-4 py-8 sm:px-8 sm:py-12">
    <header class="flex items-start gap-4">
      <span class="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-surface-gray-2">
        <Icon name="lucide-volume-2" class="size-6 text-ink-gray-7" />
      </span>
      <div class="min-w-0 flex-1">
        <p class="text-sm font-medium text-ink-gray-5">Information</p>
        <h1 class="pt-1 text-2xl font-semibold tracking-tight text-ink-gray-9 sm:text-3xl">Text to Speech</h1>
        <p class="pt-2 text-base leading-7 text-ink-gray-6">Read text aloud with your device's built-in voices.</p>
      </div>
      <Button class="h-11" variant="subtle" icon="lucide-star" :label="preferences.isFavourite(TOOL_ID) ? 'Favourited' : 'Favourite'" @click="preferences.toggleFavourite(TOOL_ID)" />
    </header>

    <div v-if="!tts.supported" class="mt-8 rounded-xl bg-surface-gray-1 px-5 py-8">
      <Icon name="lucide-volume-x" class="size-6 text-ink-gray-5" />
      <h2 class="pt-4 text-lg font-semibold text-ink-gray-9">Speech is not available in this browser</h2>
      <p class="max-w-xl pt-2 text-sm leading-6 text-ink-gray-6">This browser does not support the Web Speech API. Try a recent version of Chrome, Edge, Safari, or Firefox.</p>
    </div>

    <div v-else class="pt-8">
      <label for="tts-text" class="block text-sm font-medium text-ink-gray-7">Text</label>
      <textarea id="tts-text" v-model="tts.text.value" rows="6" class="mt-2 w-full rounded-lg border border-outline-gray-2 bg-surface-base px-3 py-2 text-base leading-7 text-ink-gray-9" placeholder="Type or paste text to read aloud" maxlength="10000"></textarea>

      <div class="grid gap-6 pt-6 sm:grid-cols-3">
        <div class="sm:col-span-3">
          <label for="tts-voice" class="block text-sm font-medium text-ink-gray-7">Voice</label>
          <FormControl id="tts-voice" type="select" size="md" class="mt-2" :model-value="tts.selectedVoiceURI.value" :options="voiceOptions" @update:model-value="tts.selectedVoiceURI.value = $event" />
          <p v-if="tts.usesNetworkVoice.value" class="pt-2 text-xs leading-5 text-ink-amber-6">This voice is provided online, so the text is sent to the voice service. Choose an “on device” voice to keep it local.</p>
        </div>
        <div>
          <label for="tts-rate" class="flex justify-between text-sm font-medium text-ink-gray-7">Speed <span class="text-ink-gray-5">{{ tts.rate.value.toFixed(1) }}×</span></label>
          <input id="tts-rate" v-model.number="tts.rate.value" type="range" min="0.5" max="2" step="0.1" class="mt-3 w-full" />
        </div>
        <div>
          <label for="tts-pitch" class="flex justify-between text-sm font-medium text-ink-gray-7">Pitch <span class="text-ink-gray-5">{{ tts.pitch.value.toFixed(1) }}</span></label>
          <input id="tts-pitch" v-model.number="tts.pitch.value" type="range" min="0" max="2" step="0.1" class="mt-3 w-full" />
        </div>
      </div>

      <div class="flex flex-wrap gap-2 pt-6">
        <Button variant="solid" icon-left="lucide-play" label="Speak" :disabled="!tts.text.value.trim()" @click="tts.speak" />
        <Button v-if="!tts.paused.value" variant="subtle" icon-left="lucide-pause" label="Pause" :disabled="!tts.speaking.value" @click="tts.pause" />
        <Button v-else variant="subtle" icon-left="lucide-play" label="Resume" @click="tts.resume" />
        <Button variant="subtle" icon-left="lucide-square" label="Stop" :disabled="!tts.speaking.value" @click="tts.stop" />
      </div>

      <p class="mt-8 border-t border-outline-gray-2 pt-5 text-xs leading-5 text-ink-gray-5">Speech is generated by your browser and operating system. On-device voices work offline and send nothing to a server.</p>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted } from 'vue'
import { Button, FormControl, Icon } from 'frappe-ui'

import { useToolboxPreferences } from '@/composables/useToolboxPreferences'
import { useTextToSpeech } from '@/tools/text-to-speech/useTextToSpeech'

const TOOL_ID = 'text-to-speech'
const preferences = useToolboxPreferences()
const tts = useTextToSpeech()

const voiceOptions = computed(() =>
  tts.voices.value.map((voice) => ({
    value: voice.voiceURI,
    label: `${voice.name} · ${voice.lang}${voice.localService ? ' · on device' : ' · online'}`,
  })),
)

onMounted(() => preferences.recordRecent(TOOL_ID))
</script>
